### PR TITLE
Bump redis version from <5 to <6

### LINKED ISSUE #458: Support for redis > 5.0.x in pyproject.toml?
my codebase depends on redis ^5.0.1 and I'm unable to use the latest version of arq with it
`redis = {extras = ["hiredis"], version = "^5.0.1"}`

```
Because no versions of arq match >0.26.0,<0.27.0
 and arq (0.26.0) depends on redis[hiredis] (>=4.2.0,<5), arq (>=0.26.0,<0.27.0) requires redis[hiredis] (>=4.2.0,<5).
So, because ... depends on both redis[hiredis] (^5.0.1) and arq (^0.26.0), version solving failed.
```

Any chance the version pinning can support updates to the 5.0.x track rather than locking to 5.0.0?

Another comment on github requesting this for a slightly different reason: https://github.com/samuelcolvin/arq/issues/441#issuecomment-2069248955

### PR DESCRIPTION
**Pull request by Wh1isper**
closes #458

Just tried to bump `redis` from `<5` to `<6`, and CI tests passed. 

redis 5 introduced some of incompatible API(`aclose` and `close`...) that made it difficult for users to change their code based on version 5, so I think bringing the version up to date it necessary.

### CODE REVIEW

**Comment by Wh1isper** [comment]
Found a need for an upgrade: https://github.com/samuelcolvin/arq/issues/418

**Comment by dbrucknr** [comment]
Is there any update on when this work might be considered for release?

**Comment by vprud** [comment]
When are you planning to release with dependency updates?

**Comment by RB387** [comment]
@chrisguidry @samuelcolvin 🙏 
This is very important PR. Redis v5 is a significant blocker

**Review by chrisguidry — APPROVED** [review]
Thanks!

**Comment by samuelcolvin** [comment]
Thanks so much.

**Comment by samuelcolvin** [comment]
Sorry for the delay in getting back to this 🙏.

**Pull request merged**
